// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmPSuDp-eEdlvAPGu8a2yLVQfaP0Nvofg',
    appId: '1:854385689677:web:d282a80ca97fcf39b70804',
    messagingSenderId: '854385689677',
    projectId: 'flutter-fire-movie',
    authDomain: 'flutter-fire-movie.firebaseapp.com',
    storageBucket: 'flutter-fire-movie.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH8kJfDKGI7C0Nfj5SDsIqCnr6U83XmTQ',
    appId: '1:854385689677:android:0b42c27f47593672b70804',
    messagingSenderId: '854385689677',
    projectId: 'flutter-fire-movie',
    storageBucket: 'flutter-fire-movie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKuyhjG4cIlSobwoXyjryQA5aRJNCe1ko',
    appId: '1:854385689677:ios:e02394e87ac6480ab70804',
    messagingSenderId: '854385689677',
    projectId: 'flutter-fire-movie',
    storageBucket: 'flutter-fire-movie.appspot.com',
    iosClientId: '854385689677-jjg3a81147a48h3d34vqr7jbpuik4kal.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKuyhjG4cIlSobwoXyjryQA5aRJNCe1ko',
    appId: '1:854385689677:ios:778804716db18bc6b70804',
    messagingSenderId: '854385689677',
    projectId: 'flutter-fire-movie',
    storageBucket: 'flutter-fire-movie.appspot.com',
    iosClientId: '854385689677-p7bo66g91j920cnq91oqrqhij1lc0jvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireMovie.RunnerTests',
  );
}
